//! Invention §53: Entropy-Beacon Commons
//!
//! Cooperative threshold public randomness beacon generated by mesh peers.
//!
//! Independent nodes contribute unpredictable local entropy from Poisson discovery
//! arrivals (§7, §28). When at least threshold k (e.g. 3) shares are collected for a given
//! epoch round, the round entropy is finalized into an unsteerable, publicly verifiable
//! 32-byte randomness beacon output.

use sha2::{Digest, Sha256};
use std::collections::HashMap;

/// An individual peer's entropy contribution for a specific round.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EntropyShare {
    pub round: u64,
    pub contributor_id: [u8; 32],
    pub entropy_bytes: [u8; 32],
}

impl EntropyShare {
    pub fn new(round: u64, contributor_id: [u8; 32], entropy_bytes: [u8; 32]) -> Self {
        Self {
            round,
            contributor_id,
            entropy_bytes,
        }
    }
}

/// The finalized, verifiable beacon randomness for an epoch round.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BeaconRandomnessOutput {
    pub round: u64,
    pub participant_count: usize,
    pub beacon_digest: [u8; 32],
}

/// Entropy Beacon Commons Engine aggregating threshold public randomness.
#[derive(Debug, Default)]
pub struct EntropyBeaconCommons {
    /// round -> contributor_id -> EntropyShare
    rounds: HashMap<u64, HashMap<[u8; 32], EntropyShare>>,
    threshold: usize,
}

impl EntropyBeaconCommons {
    pub fn new(threshold: usize) -> Self {
        Self {
            rounds: HashMap::new(),
            threshold: threshold.max(2),
        }
    }

    /// Submit an entropy share for a round.
    pub fn submit_share(&mut self, share: EntropyShare) {
        self.rounds
            .entry(share.round)
            .or_default()
            .insert(share.contributor_id, share);
    }

    /// Try finalizing beacon output for a round once threshold is reached.
    pub fn try_finalize_round(&self, round: u64) -> Option<BeaconRandomnessOutput> {
        let shares_map = self.rounds.get(&round)?;
        if shares_map.len() < self.threshold {
            return None;
        }

        // Sort contributors for deterministic output aggregation
        let mut sorted_shares: Vec<&EntropyShare> = shares_map.values().collect();
        sorted_shares.sort_by_key(|s| s.contributor_id);

        let mut hasher = Sha256::new();
        hasher.update(b"GGN_ENTROPY_BEACON_COMMONS_V1");
        hasher.update(&round.to_be_bytes());
        for s in &sorted_shares {
            hasher.update(&s.contributor_id);
            hasher.update(&s.entropy_bytes);
        }
        let beacon_digest: [u8; 32] = hasher.finalize().into();

        Some(BeaconRandomnessOutput {
            round,
            participant_count: sorted_shares.len(),
            beacon_digest,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_entropy_beacon_commons_threshold_finalization() {
        let mut commons = EntropyBeaconCommons::new(3);
        let round = 101;

        let node1 = [0x11u8; 32];
        let node2 = [0x22u8; 32];
        let node3 = [0x33u8; 32];

        // 1. Submit 2 shares: below threshold 3 -> cannot finalize
        commons.submit_share(EntropyShare::new(round, node1, [0xAAu8; 32]));
        commons.submit_share(EntropyShare::new(round, node2, [0xBBu8; 32]));
        assert!(commons.try_finalize_round(round).is_none());

        // 2. Submit 3rd share: reaches threshold -> finalizes deterministic beacon output!
        commons.submit_share(EntropyShare::new(round, node3, [0xCCu8; 32]));
        let output = commons.try_finalize_round(round).expect("finalizes");
        assert_eq!(output.round, round);
        assert_eq!(output.participant_count, 3);
        assert_ne!(output.beacon_digest, [0u8; 32]);

        // 3. Determinism: calling again produces identical beacon digest
        let output2 = commons.try_finalize_round(round).unwrap();
        assert_eq!(output.beacon_digest, output2.beacon_digest);
    }
}
