# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: KellerSystems.Vantablack
PackageVersion: 0.8.11
InstallerType: inno
Scope: user
InstallModes:
  - interactive
  - silent
  - silentWithProgress
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /SILENT /SUPPRESSMSGBOXES /NORESTART
UpgradeBehavior: install
FileExtensions:
  - key
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/KELLERBABG/Vantablack/releases/download/v0.8.11/ggn-0.8.11-windows-setup.exe
    ProductCode: '{8E98B1C2-824A-4835-B5E3-A5B4C3D2E1F0}_is1'
ManifestType: installer
ManifestVersion: 1.6.0
